-- AUTO-GENERATED by `mcpp emit xpkg`. Do not edit by hand.
-- Source: mcpp.toml @ v0.2.2
package = {
    spec = "1",
    name = "tensorvia-cpu",
    description = "CPU backend of Tensorvia, ported to C++23 modules",
    licenses = {"MIT"},
    repo = "https://github.com/Aimol-l/Tensorvia-cpu",
    type = "package",
    namespace  = "aimol",
    maintainers = {"Aimol-l"},
    
    xpm = {
        linux   = {
        ['0.2.2'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.2/tensorvia-cpu-0.2.2.tar.gz", sha256 = "e4086c330b63247469a2cc799cfc02d236df9682e5ce1dc2269ac41ed08f9c24" },
        },
        macosx  = {
        ['0.2.2'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.2/tensorvia-cpu-0.2.2.tar.gz", sha256 = "e4086c330b63247469a2cc799cfc02d236df9682e5ce1dc2269ac41ed08f9c24" },
        },
        windows = {
        ['0.2.2'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.2/tensorvia-cpu-0.2.2.tar.gz", sha256 = "e4086c330b63247469a2cc799cfc02d236df9682e5ce1dc2269ac41ed08f9c24" },
        },
    },
}
