-- AUTO-GENERATED by `mcpp emit xpkg`. Do not edit by hand.
-- Source: mcpp.toml @ v0.1.1
--
-- Hand-edit on top of the generated file: `mcpp emit xpkg` writes the bare
-- project name and no `namespace`; the `namespace = "aimol"` line below was
-- added when the package was filed into this index, which made `name` the
-- split form and left the package uninstallable (xlings keyed the entry under
-- `tensorvia-cpu` while mcpp asks for `aimol.tensorvia-cpu`). `name` is now
-- the fully-qualified spelling. See mcpp-community/mcpp#278.
package = {
    spec = "1",
    name = "aimol.tensorvia-cpu",
    description = "CPU backend of Tensorvia, ported to C++23 modules",
    licenses = {"MIT"},
    repo = "https://github.com/Aimol-l/Tensorvia-cpu",
    type = "package",
    namespace  = "aimol",
    maintainers = {"Aimol-l"},

    xpm = {
        linux   = {
        ['0.1.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.1.1/tensorvia-cpu-0.1.1.tar.gz", sha256 = "3732dd3f43dc540d5e7f9707d60608f465e0bbff8c88064c3f4198cdc5cb28b2" },
        },
        macosx  = {
        ['0.1.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.1.1/tensorvia-cpu-0.1.1.tar.gz", sha256 = "3732dd3f43dc540d5e7f9707d60608f465e0bbff8c88064c3f4198cdc5cb28b2" },
        },
        windows = {
        ['0.1.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.1.1/tensorvia-cpu-0.1.1.tar.gz", sha256 = "3732dd3f43dc540d5e7f9707d60608f465e0bbff8c88064c3f4198cdc5cb28b2" },
        },
    },
}
