-- AUTO-GENERATED by `mcpp emit xpkg`. Do not edit by hand.
-- Source: mcpp.toml @ v0.2.1
package = {
    spec = "1",
    namespace  = "aimol",
    name = "tensorvia-cpu",
    description = "CPU backend of Tensorvia, ported to C++23 modules",
    licenses = {"MIT"},
    repo = "https://github.com/Aimol-l/Tensorvia-cpu",
    type = "package",

    xpm = {
        linux   = {
        ['0.2.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.1/tensorvia-cpu-0.2.1.tar.gz", sha256 = "cdca93b2dbdcb46e163e787e3da735427d0cf4f3e8f9a4551bd1f50237389420" },
        },
        macosx  = {
        ['0.2.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.1/tensorvia-cpu-0.2.1.tar.gz", sha256 = "cdca93b2dbdcb46e163e787e3da735427d0cf4f3e8f9a4551bd1f50237389420" },
        },
        windows = {
        ['0.2.1'] = { url = "https://github.com/Aimol-l/Tensorvia-cpu/releases/download/v0.2.1/tensorvia-cpu-0.2.1.tar.gz", sha256 = "cdca93b2dbdcb46e163e787e3da735427d0cf4f3e8f9a4551bd1f50237389420" },
        },
    },
}
