-- AUTO-GENERATED by `mcpp emit xpkg`. Do not edit by hand.
-- Source: mcpp.toml @ v3.19.1
package = {
    spec = "1",
    name = "protobuf",
    description = "Protocol Buffers - Google's data interchange format (modularized from OpenCV 3rdparty)",
    licenses = {"BSD-3-Clause"},
    repo = "https://github.com/Aimol-l/protobuf-mcpp.git",
    type = "package",
    namespace  = "aimol",
    maintainers = {"Aimol-l"},
    
    xpm = {
        linux   = {
        ['3.19.1'] = { url = "https://github.com/Aimol-l/protobuf-mcpp/releases/download/v3.19.1/protobuf-3.19.1.tar.gz", sha256 = "9bcc197b31f84089cac5ca1e57b0e81aec4e6d88481cccf729fdb8bea6a52463" },
        },
        macosx  = {
        ['3.19.1'] = { url = "https://github.com/Aimol-l/protobuf-mcpp/releases/download/v3.19.1/protobuf-3.19.1.tar.gz", sha256 = "9bcc197b31f84089cac5ca1e57b0e81aec4e6d88481cccf729fdb8bea6a52463" },
        },
        windows = {
        ['3.19.1'] = { url = "https://github.com/Aimol-l/protobuf-mcpp/releases/download/v3.19.1/protobuf-3.19.1.tar.gz", sha256 = "9bcc197b31f84089cac5ca1e57b0e81aec4e6d88481cccf729fdb8bea6a52463" },
        },
    },
}
