-- freedesktop.opengl — libOpenGL.so.0, plus `import khronos.opengl;`.
--
-- version-neutral OpenGL dispatched through GLVND. This is the half that was missing: with
-- `freedesktop.egl` a project could reach `eglInitialize` and then had no GL
-- to call. A Wayland compositor takes its context through EGL and draws with
-- GLES2, so without this the render chain stopped one step short.
--
-- ─────────────────────────────────────────────────────────────────────────
-- SHAPE: a source build, out of the same fork as freedesktop.egl
--
-- Same criterion, same fork, same reasoning as that package: libglvnd is a
-- separable project, so it is built rather than bound. `libGLdispatch.so.0`
-- comes from a sibling workspace member by PATH — being the ONE dispatch point
-- in a process is what GLVND exists for, and every GL entry point in this
-- library routes through it, so the two must be one build.
--
-- The ecosystem payload `xim:libglvnd` ships the same soname, and binding it
-- instead would work by soname reuse — measured. It is still a source build,
-- because a payload library carries a DT_NEEDED on `libGLdispatch.so.0` and
-- would then be dispatching through a DIFFERENT build of GLVND than the one
-- this index provides, with only `__glDispatchGetABIVersion` between that and
-- a runtime failure.
--
-- NOT to be confused with `compat.opengl`, which ships the Khronos GL
-- HEADERS from the OpenGL-Registry and no library. This one is the library.
--
-- ─────────────────────────────────────────────────────────────────────────
-- THE MODULE IS NAMED FOR THE SPECIFICATION
--
-- `khronos.opengl`, not `freedesktop.opengl`, and the package/module mismatch is
-- deliberate: freedesktop hosts libglvnd, but version-neutral OpenGL is a **Khronos**
-- specification with several implementations. A module name is global and
-- permanent in a way a package name is not, so it names the INTERFACE's owner.
-- Same rule as `khronos.egl`; `mcpplibs.openkal` paid for it (its 0.1.0 was
-- withdrawn for putting the imported module under the implementation's
-- control).
--
-- THE EXPORT LIST IS THE HEADER INTERSECTED WITH THE LIBRARY, generated by the
-- fork's `mcpp/tools/genglmod.sh` and diffed by its CI. A header can declare
-- more than its library dispatches, so exporting the header wholesale would
-- put names in the module that do not link.
--
-- The `GL_*` CONSTANTS are macros and no module can export a macro: include
-- the same header beside the import when you need `GL_COLOR_BUFFER_BIT`.
package = {
    spec        = "1",
    namespace   = "freedesktop",
    name        = "opengl",
    description = "libOpenGL.so.0 — version-neutral OpenGL through GLVND, built from source, with a C++23 module",
    licenses    = {"MIT"},
    repo        = "https://github.com/mcpplibs/libglvnd",
    type        = "package",

    xpm = {
        linux = {
            -- libglvnd's version, as with freedesktop.egl: what a consumer
            -- pins is which libglvnd it links, not which GL spec level.
            ["1.7.0"] = {
                url = {
                    GLOBAL = "https://github.com/mcpplibs/libglvnd/archive/refs/tags/v1.7.0.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/libglvnd/releases/download/1.7.0/libglvnd-1.7.0.tar.gz",
                },
                sha256 = "11347b0ffffbcb9ca51cd3941dff9ef923b21bb1e9469f3e5cff42ed487bf77d",
            },
        },
    },

    mcpp = "*/mcpp/opengl/mcpp.toml",
}
